# Generated by Django 5.2.3 on 2025-06-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yum_parser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='repository',
        ),
        migrations.DeleteModel(
            name='Dependency',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
