# Generated by Django 5.2.3 on 2025-07-07 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package_nevra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nevra', models.CharField(max_length=255)),
                ('obsoletes', models.TextField(blank=True, null=True)),
                ('conflicts', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('name', 'nevra')},
            },
        ),
        migrations.CreateModel(
            name='Tracked_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('repos', models.TextField(default='[]')),
            ],
            options={
                'unique_together': {('session_key', 'name', 'repos')},
            },
        ),
        migrations.CreateModel(
            name='Package_repos_graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repos', models.TextField(default='[]')),
                ('graph_json', models.TextField(default='{}')),
                ('package_nevra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yum_parser.package_nevra')),
            ],
            options={
                'unique_together': {('package_nevra', 'repos')},
            },
        ),
    ]
