# Generated by Django 5.2.3 on 2025-07-08 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracked_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('repos_hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Repo_path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yum_parser.base_url')),
            ],
        ),
        migrations.CreateModel(
            name='Package_nevra_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nevra', models.CharField(max_length=255)),
                ('obsoletes', models.TextField(blank=True, null=True)),
                ('conflicts', models.TextField(blank=True, null=True)),
                ('graph_json', models.TextField(default='{}')),
                ('tracked_package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package_info', to='yum_parser.tracked_package')),
            ],
        ),
        migrations.CreateModel(
            name='Tracked_package_repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yum_parser.repo_path')),
                ('tracked_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yum_parser.tracked_package')),
            ],
        ),
    ]
