# Generated by Django 5.2.3 on 2025-07-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yum_parser', '0002_remove_package_repository_delete_dependency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('session_key', 'name')},
            },
        ),
    ]
