# Generated by Django 5.2.3 on 2025-07-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yum_parser', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedPackageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nevra', models.CharField(max_length=255, unique=True)),
                ('obsoletes', models.TextField(blank=True, null=True)),
                ('conflicts', models.TextField(blank=True, null=True)),
                ('graph_json', models.TextField()),
            ],
            options={
                'unique_together': {('name', 'nevra')},
            },
        ),
    ]
